name: ClusterFuzzLite cron tasks

on: workflow_dispatch

permissions: read-all

jobs:
  Pruning:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: go
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 120
          mode: "prune"
          output-sarif: true
          # Optional but recommended.
          # See later section on "Git repo for storage".
          storage-repo: https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/NishantBansal2003/fuzzing-storage.git
          storage-repo-branch: main # Optional. Defaults to "main"
          storage-repo-branch-coverage: gh-pages # Optional. Defaults to "gh-pages".
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  Coverage:
    needs: Pruning
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: go
          sanitizer: coverage
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: "coverage"
          sanitizer: "coverage"
          # Optional but recommended.
          # See later section on "Git repo for storage".
          storage-repo: https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/NishantBansal2003/fuzzing-storage.git
          storage-repo-branch: main # Optional. Defaults to "main"
          storage-repo-branch-coverage: gh-pages # Optional. Defaults to "gh-pages".
        env:
          # Pass PAT as environment variable for API calls
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
